# Namespace can be omitted to use the Helm release namespace
namespace: rook-ceph

image:
  repository: ghcr.io/csc478-wcu/cc2-frontend
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
