---
# roles/base/tasks/main.yml
# -------------------------
# Base system configuration for Kubernetes cluster nodes.
# Includes apt setup, kernel modules, sysctl, and swap disable.

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - git
      - python3-pip
    state: present

# --- Kernel + sysctl configuration ---
- name: Ensure k8s modules load at boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load kernel modules immediately
  ansible.builtin.command: modprobe {{ item }}
  loop:
    - overlay
    - br_netfilter
  changed_when: false
  failed_when: false

- name: Configure sysctl for Kubernetes networking
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    mode: '0644'

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  changed_when: false

# --- Swap must be disabled for kubelet ---
- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  changed_when: false
  failed_when: false

- name: Ensure swap is disabled in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.+\s+swap\s+.+)$'
    replace: '# \1'
  failed_when: false

# --- Clone CampusConnect Helm charts ---
- name: Ensure local repository directory exists
  ansible.builtin.file:
    path: "/users/{{ ansible_ssh_user }}/local/repository"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: '0755'

- name: Clone CampusConnect repo (for Helm charts)
  ansible.builtin.git:
    repo: "https://github.com/CSC478-WCU/CC2-Cluster.git"
    dest: "/users/{{ ansible_ssh_user }}/local/repository"
    version: "{{ branch | default('main') }}"
    force: yes
    update: yes