{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
{{- end }}
