apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  serviceName: mongo
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: { app: mongo }
  template:
    metadata:
      labels: { app: mongo }
    spec:
      containers:
        - name: mongo
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.auth.enabled }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: { secretKeyRef: { name: mongo-auth, key: username } }
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: mongo-auth, key: password } }
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.auth.database | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
