---
# roles/containerd/tasks/main.yml
# -------------------------------
# Install and configure containerd as the Kubernetes container runtime.

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install containerd package
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Configure containerd with systemd cgroups
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: |
      version = 2
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "registry.k8s.io/pause:3.9"
        [plugins."io.containerd.grpc.v1.cri".containerd]
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              runtime_type = "io.containerd.runc.v2"
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                SystemdCgroup = true
    mode: '0644'

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Wait for containerd socket
  ansible.builtin.wait_for:
    path: /run/containerd/containerd.sock
    state: present
    timeout: 30
