apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
