---
# roles/metallb/tasks/main.yml
# ----------------------------
# Install and configure MetalLB for LoadBalancer services.

- name: Get primary interface CIDR
  ansible.builtin.command: ip -4 addr show dev eno1
  register: ip_addr
  changed_when: false

- name: Extract subnet base
  ansible.builtin.set_fact:
    node_cidr: "{{ ip_addr.stdout | regex_search('inet ([0-9.]+/[0-9]+)', '\\1') }}"
    subnet_base: "{{ node_cidr.split('/')[0].rsplit('.', 1)[0] }}"
    metallb_range: "{{ subnet_base }}.200-{{ subnet_base }}.220"

- name: Install MetalLB manifests
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml

- name: Wait for MetalLB controller rollout
  ansible.builtin.command: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf
    -n metallb-system rollout status deployment/controller --timeout=180s
  changed_when: false

- name: Configure MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default-pool
        namespace: metallb-system
      spec:
        addresses:
          - "{{ metallb_range }}"

- name: Configure MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default
        namespace: metallb-system
      spec:
        ipAddressPools:
          - default-pool
