---
# roles/external-dns/tasks/main.yml
# ---------------------------------
# Install ExternalDNS with Cloudflare provider.

- name: Add bitnami repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy external-dns (Bitnami image)
  kubernetes.core.helm:
    name: external-dns
    chart_ref: bitnami/external-dns
    release_namespace: external-dns
    create_namespace: true
    kubeconfig: /etc/kubernetes/admin.conf
    wait: true
    atomic: true
    timeout: "900s"
    values:
      rbac:
        create: true
      image:
        repository: bitnami/external-dns
        tag: 0.14.2
        pullPolicy: IfNotPresent
      sources:
        - ingress
        - service
      provider: cloudflare
      cloudflare:
        apiToken: "{{ cloudflare_api_token }}"
        proxied: false
      domainFilters:
        - campusconnectwcu.com
      policy: upsert-only
      txtOwnerId: campusconnect
      interval: 1m
      logLevel: info
