# roles/external-dns/tasks/main.yml
# ---------------------------------
# Install ExternalDNS (official Kubernetes SIGs chart) with Cloudflare provider.

- name: Add ExternalDNS official Helm repo
  kubernetes.core.helm_repository:
    name: external-dns
    repo_url: https://kubernetes-sigs.github.io/external-dns/

- name: Ensure external-dns namespace exists
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-dns

- name: Create Cloudflare API token secret
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token
        namespace: external-dns
      type: Opaque
      stringData:
        CF_API_TOKEN: "{{ cloudflare_api_token }}"

- name: Deploy ExternalDNS (official chart)
  kubernetes.core.helm:
    name: external-dns
    chart_ref: external-dns/external-dns
    release_namespace: external-dns
    create_namespace: false
    kubeconfig: /etc/kubernetes/admin.conf
    wait: true
    atomic: true
    timeout: "900s"
    values:
      provider: cloudflare
      env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: CF_API_TOKEN
      sources:
        - ingress
        - service
      domainFilters:
        - campusconnectwcu.com
      policy: upsert-only
      txtOwnerId: campusconnect
      interval: 1m
      logLevel: info
