# roles/external-dns/tasks/main.yml
# ---------------------------------
# Install ExternalDNS with Cloudflare provider (using GHCR image).

- name: Ensure external-dns namespace exists
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-dns

- name: Create Cloudflare API token secret
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: external-dns-env
        namespace: external-dns
      type: Opaque
      stringData:
        CF_API_TOKEN: "{{ cloudflare_api_token }}"

- name: Add Bitnami Helm repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy ExternalDNS (GHCR image)
  kubernetes.core.helm:
    name: external-dns
    chart_ref: bitnami/external-dns
    release_namespace: external-dns
    create_namespace: false
    kubeconfig: /etc/kubernetes/admin.conf
    wait: true
    atomic: true
    timeout: "900s"
    values:
      rbac:
        create: true
      image:
        repository: ghcr.io/kubernetes-sigs/external-dns/external-dns
        tag: v0.19.0
        pullPolicy: IfNotPresent
      provider: cloudflare
      extraEnvVarsSecret: external-dns-env  
      sources:
        - ingress
        - service
      domainFilters:
        - campusconnectwcu.com
      policy: upsert-only
      txtOwnerId: campusconnect
      interval: 1m
      logLevel: info
