apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector: { app: redis }
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
