# -------------------
# Install dependencies on all CloudLab nodes
# -------------------
- name: Install dependencies on all CloudLab nodes
  hosts: cloudlab_nodes
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - git
        state: present

    # -------------------
    # containerd setup
    # -------------------
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key for containerd
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add containerd apt repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: containerd

    - name: Install containerd
      ansible.builtin.apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Configure containerd with systemd cgroup + CRI enabled
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        # Ensure CRI plugin block exists
        grep '\[plugins."io.containerd.grpc.v1.cri"\]' /etc/containerd/config.toml || \
          echo '[plugins."io.containerd.grpc.v1.cri"]' >> /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        enabled: yes
        state: restarted

    # -------------------
    # Kubernetes (kubectl + kubeadm + kubelet)
    # -------------------
    - name: Download Kubernetes GPG key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes apt repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubeadm, kubelet, kubectl
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kube packages at current version
      ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl

    # -------------------
    # Helm install
    # -------------------
    - name: Download Helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0755'

    - name: Run Helm install script
      ansible.builtin.command: /tmp/get-helm-3
      args:
        creates: /usr/local/bin/helm

    # -------------------
    # Verify installs
    # -------------------
    - name: Check versions
      ansible.builtin.command: "{{ item }}"
      loop:
        - containerd --version
        - kubeadm version
        - kubelet --version
        - kubectl version --client
        - helm version
        - git --version
      register: version_output
      ignore_errors: yes

    - ansible.builtin.debug:
        var: version_output.results
