---
- name: Install dependencies on all CloudLab nodes
  hosts: cloudlab_nodes
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - git
        state: present

    # -------------------
    # Install Docker
    # -------------------
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Enable and start Docker
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # -------------------
    # Install kubectl (latest via pkgs.k8s.io)
    # -------------------
    - name: Create keyrings directory for Kubernetes
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes apt repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes

    # -------------------
    # Install Helm
    # -------------------
    - name: Download Helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0755'

    - name: Run Helm install script
      ansible.builtin.command: /tmp/get-helm-3
      args:
        creates: /usr/local/bin/helm

    # -------------------
    # Verify installs
    # -------------------
    - name: Check versions
      ansible.builtin.command: "{{ item }}"
      loop:
        - docker --version
        - kubectl version --client --short
        - helm version --short
        - git --version
      register: version_output
      ignore_errors: yes

    - ansible.builtin.debug:
        var: version_output.results
