apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: minio }
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
