apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: minio }
  ports:
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
