apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
spec:
  serviceName: minio
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: { app: minio }
  template:
    metadata:
      labels: { app: minio }
    spec:
      containers:
        - name: minio
          image: {{ .Values.image }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.service.consolePort }}"
          envFrom:
            - secretRef: { name: minio-creds }
          ports:
            - containerPort: {{ .Values.service.apiPort }}
            - containerPort: {{ .Values.service.consolePort }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
