---
# roles/kubeadm-init/tasks/main.yml
# ---------------------------------
# Initialize Kubernetes control-plane node with kubeadm.

- name: Sanity check CRI
  ansible.builtin.command: crictl info
  changed_when: false

- name: Run kubeadm init
  ansible.builtin.command: >
    kubeadm init
    --pod-network-cidr=10.244.0.0/16
    --cri-socket=unix:///run/containerd/containerd.sock
    --v=5
    --ignore-preflight-errors=all
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result
  failed_when: kubeadm_init_result.rc != 0

- name: Debug kubeadm init output
  ansible.builtin.debug:
    var: kubeadm_init_result
  when: kubeadm_init_result.rc != 0

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_ssh_user }}/.kube"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0755'
  become: yes

- name: Copy kubeconfig for SSH user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_ssh_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0644'
  become: yes

- name: Wait for control plane to be ready
  ansible.builtin.command: kubectl get nodes --kubeconfig=/etc/kubernetes/admin.conf
  register: kubectl_nodes
  until: kubectl_nodes.rc == 0
  retries: 30
  delay: 10
  changed_when: false

- name: Wait for kube-system pods to be ready
  ansible.builtin.command: kubectl get pods -n kube-system --kubeconfig=/etc/kubernetes/admin.conf
  register: kubectl_pods
  until: kubectl_pods.rc == 0
  retries: 10
  delay: 5
  changed_when: false

- name: Generate kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command
  timeout: 60
  no_log: true

- name: Save join script locally
  delegate_to: localhost
  run_once: true
  ansible.builtin.copy:
    dest: "/tmp/kubeadm_join.sh"
    content: |
      #!/bin/bash
      {{ join_command.stdout }}
    mode: '0755'
  no_log: true
