---
# roles/metrics/tasks/main.yml
# ----------------------------
# Deploy Prometheus + Grafana monitoring stack.

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    kubeconfig: /etc/kubernetes/admin.conf
    create_namespace: true
    values_files:
      - "/users/{{ ansible_user }}/local/repository/helm/metrics/values.yaml"
    wait: true
    timeout: "600s"
