# roles/metallb/tasks/main.yml
# ----------------------------
# Install and configure MetalLB for LoadBalancer services.

- name: Get default interface
  ansible.builtin.command: ip route show default
  register: default_route
  changed_when: false

- name: Extract default interface name
  ansible.builtin.set_fact:
    primary_iface: "{{ (default_route.stdout | regex_search('dev (\\S+)', '\\1')) | first }}"

- name: Debug detected primary interface
  ansible.builtin.debug:
    msg: "Primary interface detected: {{ primary_iface }}"

- name: Get primary interface CIDR
  ansible.builtin.command: ip -4 addr show dev {{ primary_iface }}
  register: ip_addr
  changed_when: false

- name: Extract node CIDR
  ansible.builtin.set_fact:
    node_cidr: "{{ (ip_addr.stdout | regex_search('inet (\\d+\\.\\d+\\.\\d+\\.\\d+/\\d+)', '\\1')) | first }}"
  failed_when: node_cidr is not defined or node_cidr == ''

- name: Debug extracted CIDR
  ansible.builtin.debug:
    msg: "Node CIDR detected: {{ node_cidr }}"

- name: Compute subnet base
  ansible.builtin.set_fact:
    subnet_base: "{{ node_cidr.split('/')[0].rsplit('.', 1)[0] }}"

- name: Compute MetalLB range
  ansible.builtin.set_fact:
    metallb_range: "{{ subnet_base }}.200-{{ subnet_base }}.220"

- name: Debug MetalLB range
  ansible.builtin.debug:
    msg: "MetalLB range: {{ metallb_range }}"

- name: Install MetalLB manifests
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml

- name: Wait for MetalLB controller rollout
  ansible.builtin.command: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf
    -n metallb-system rollout status deployment/controller --timeout=180s
  changed_when: false

- name: Configure MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default-pool
        namespace: metallb-system
      spec:
        addresses:
          - "{{ metallb_range }}"

- name: Configure MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default
        namespace: metallb-system
      spec:
        ipAddressPools:
          - default-pool
