name: Ansible Deploy (Reusable)

on:
  workflow_call:
    inputs:
      nodes_json: { required: true, type: string }
      ssh_user: { required: true, type: string }
      branch: { required: true, type: string }
    secrets:
      CLOUDLAB_PEM_B64: { required: true }
      ANSIBLE_VAULT_PASSWORD: { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install Ansible collections
        run: ansible-galaxy collection install kubernetes.core

      - name: Recreate SSH key from secret
        run: |
          echo "${CLOUDLAB_PEM_B64}" | base64 -d > cloudlab_decrypted.pem
          chmod 600 cloudlab_decrypted.pem
        env:
          CLOUDLAB_PEM_B64: ${{ secrets.CLOUDLAB_PEM_B64 }}

      - name: ansible.cfg
        run: |
          cat > ansible.cfg <<EOF
          [defaults]
          private_key_file = ${GITHUB_WORKSPACE}/cloudlab_decrypted.pem
          host_key_checking = False
          forks = 20
          timeout = 30
          [ssh_connection]
          pipelining = True
          EOF

      - name: Write vault password file
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass.txt
          chmod 600 .vault_pass.txt
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Run cluster bootstrap
        run: |
          ansible-playbook -i localhost, ansible/playbooks/bootstrap.yml \
            --vault-password-file .vault_pass.txt \
            -e nodes_json='${{ inputs.nodes_json }}' \
            -e ssh_user='${{ inputs.ssh_user }}'
