---
# roles/cni-flannel/tasks/main.yml
# --------------------------------
# Install Flannel CNI plugin for pod networking.

- name: Apply Flannel manifest
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    kubeconfig: /etc/kubernetes/admin.conf

- name: Wait for Flannel rollout
  ansible.builtin.command: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf
    -n kube-flannel rollout status ds/kube-flannel-ds --timeout=180s
  changed_when: false
  failed_when: false
